### ISSUE TITLE
Name Conflict with Perfectro Forbidden lands module.

### ISSUE THREAD

**Issue by cateland** [LeonardoFacchin/Forbidden-Lands-System-FVTT#1]
Your module name conflict with Perfectro published one.
This seem to create an issue where no assets could load on any sheet if his module is already installed.
This should probably be forwarded to the foundry repository if the cause is foundry mixing up thing on modules with same names.

**Comment by LeonardoFacchin** [comment]
Thanks for the heads up. I'll check Perfectro's system and try to change my system's name to resolve the conflict
