### ISSUE TITLE
file name case.

### ISSUE THREAD

**Issue by cateland** [LeonardoFacchin/Forbidden-Lands-System-FVTT#2]
Looks like on case sensitive systems the config file cannot be loaded since it is imported as config.js and the file is name Config.js

https://github.com/LeonardoFacchin/Foundry-VTT-Forbidden-Lands-System/blob/70b15c1bddccfc250791d82d648c75953bf57b2f/module/helper-functions.js#L9

**Comment by LeonardoFacchin** [comment]
Thanks again for the report. The name case should now be set to the correct Config.js through all the relevant files. I will leave this issue open in case something went wrong and close it towmorrow if everything is ok.
